---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: vedikaui
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vedikaui
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: vedikaui
    spec:
      containers:
      - name: vedikaui
        image: shivastunts/angularuikube
        ports:
        - containerPort: 4200
